create database DBT_SNW
create database ANALYTICS

CREATE OR REPLACE TABLE GLUE_DATA.ORDERS.ORDER_ITEMS (
    ORDER_ITEM_ID             INTEGER,
    ORDER_ITEM_ORDER_ID       INTEGER,
    ORDER_ITEM_PRODUCT_ID     INTEGER,
    ORDER_ITEM_QUANTITY       INTEGER,
    ORDER_ITEM_SUBTOTAL       NUMBER(10,2),
    ORDER_ITEM_PRODUCT_PRICE  NUMBER(10,2)
);

CREATE OR REPLACE TABLE GLUE_DATA.ORDERS.DEPARTMENTS (
    DEPARTMENT_ID    INTEGER,
    DEPARTMENT_NAME  STRING
);

CREATE OR REPLACE TABLE GLUE_DATA.ORDERS.CATEGORIES (
    CATEGORY_ID               INTEGER,
    CATEGORY_DEPARTMENT_ID    INTEGER,
    CATEGORY_NAME             STRING
);

CREATE OR REPLACE TABLE GLUE_DATA.ORDERS.CUSTOMERS (
    CUSTOMER_ID        INTEGER,
    CUSTOMER_FNAME     STRING,
    CUSTOMER_LNAME     STRING,
    CUSTOMER_EMAIL     STRING,
    CUSTOMER_PASSWORD  STRING,
    CUSTOMER_STREET    STRING,
    CUSTOMER_CITY      STRING,
    CUSTOMER_STATE     STRING,
    CUSTOMER_ZIPCODE   STRING
);

CREATE OR REPLACE TABLE GLUE_DATA.ORDERS.PRODUCTS (
    PRODUCT_ID              INTEGER,
    PRODUCT_CATEGORY_ID     INTEGER,
    PRODUCT_NAME            STRING,
    PRODUCT_DESCRIPTION     STRING,
    PRODUCT_PRICE           NUMBER(10,2),
    PRODUCT_IMAGE           STRING
);