SELECT 'ORDERS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM GLUE_DATA.ORDERS.ORDERS

UNION ALL

SELECT 'ORDER_ITEMS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM GLUE_DATA.ORDERS.ORDER_ITEMS

UNION ALL

SELECT 'DEPARTMENTS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM GLUE_DATA.ORDERS.DEPARTMENTS

UNION ALL

SELECT 'CATEGORIES' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM GLUE_DATA.ORDERS.CATEGORIES

UNION ALL

SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM GLUE_DATA.ORDERS.CUSTOMERS

UNION ALL

SELECT 'PRODUCTS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM GLUE_DATA.ORDERS.PRODUCTS;